### ISSUE TITLE
Apple has bad selection box

### ISSUE THREAD

**Issue by Wuzzy2** [CasimirKaPazi/Voxelgarden#57]
The selection box of the apple is bad and really annoying. It's way above the actual apple, so it always annoys me when I try to pick up an apple.
Please try to make the selection match the apple as close as possible.

Version: 5.0.0

**Comment by CasimirKaPazi** [comment]
The main problem is that apples are attached nodes, but the selection box stays the same independent from where they are attached to.

They are attached because of leaf decay. Apples should fall down two as nodes, but can't be just falling nodes. I think the best fix would be to remove the attached property completely (as it also causes other issues) and include apples into leaf decay to trigger falling once just as with saplings.

**Comment by Wuzzy2** [comment]
Another idea would be to split apples into 2 nodes and change code accordingly. That's obviously a bit ugly code-wise, but allows you to have free choice over selectionboxes.

But your idea sounds good, too.

**Comment by CasimirKaPazi** [comment]
I have been trying many things, messing with leafdecay and torchlike drawtype, but then I realized that I could just fix the selection box to one kind, regardless where it is attached to. It's still ugly to use attached for apples, but better than the alternatives I tried.
