### ISSUE TITLE
Mobs never drop anything

### ISSUE THREAD

**Issue by Wuzzy2** [CasimirKaPazi/Voxelgarden#59]
No idea if it's intentional, but mobs never drop anything.

Game version: 5.0.0
Minetest version: 5.0.1

**Comment by MarSoft** [comment]
According to code it is intentional, but is annoying.

**Comment by CasimirKaPazi** [comment]
It is intentional. Mobs are meant to be a thread, not a piñata. But I also understand that it you have to defend against them and get nothing in return.

If there are drops they should be 1. not worth very much (i.e. no mob farms) 2. specific to the type of mob (probably new items). One thing I actually wanted to add is to have the dustdevils (the horned ones) throw spears and when killed drop them.
I am open to suggestions.

**Comment by Wuzzy2** [comment]
It's weird that rats don't drop rat meat when you kill them. You have to rightclick them because … ?

Unique, mob-specific items that you cannot get anywhere else would be definitely a good idea IF they integrate well into game (of course).

**Comment by LoneWolfHT** [comment]
Maybe when a mob dies spawn a 'mob caracass' or something where it died and allow the player to cut meat/hide off of the node

**Comment by CasimirKaPazi** [comment]
I have added some drops, without creating new items. If someone has any better idea, I'm open for suggestions.
See: ba84037
